version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - .:/workspace:cached

    ports:
      - "5173:5173"

    working_dir: /workspace
    command: sleep infinity


